### ISSUE TITLE
[BGE-19] Occasional Crashing On Entity Pickup?

### ISSUE THREAD

**Issue by RedBeardsCode** [jb0s/blockgame-enhanced#11]
**Describe the bug**
Occasional crashing while mining/digging and pushing forward at the same time (no room between player and block)

**To Reproduce**
Unsure, this doesn't happen often but this is like the 6-7th time I've had this happen.
Perhaps it happens when an entity is picked up at the same time it has been grouped with other entities by the server? Unsure.

**Expected behavior**
No Crash on item pickups

**Actual behavior**
Crashed on item pickups

**Screenshots**
N/A
Full Crash To Launcher

**Desktop (please complete the following information):**
 - OS: Windows 11 (gross, I know)
 - List of all mods you're using:  Fabric API 0.76.0+1.18.2, Cloth Config v6 6.5.102, Journeymap-Fabric 5.9.7, Blockgame Enhanced 1.2.4

**Additional context**

The ArrayIndexOutOfBoundsException has occured with different array length (1, 2, and 3) as far as I've seen.
 
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/30/23, 7:58 AM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/java.util.LinkedHashMap.valuesToArray(LinkedHashMap.java:555)
	at java.base/java.util.LinkedHashMap$LinkedValues.toArray(LinkedHashMap.java:639)
	at dev.jb0s.blockgameenhanced.gui.hud.immersive.widget.pickups.ImmersivePickupStream.getPickupsSafe(ImmersivePickupStream.java:90)
	at dev.jb0s.blockgameenhanced.gui.hud.immersive.widget.pickups.ImmersivePickupStream.render(ImmersivePickupStream.java:23)
	at dev.jb0s.blockgameenhanced.gui.hud.immersive.ImmersiveIngameHud.method_1759(ImmersiveIngameHud.java:49)
	at net.minecraft.class_329.method_1753(class_329.java:226)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.LinkedHashMap.valuesToArray(LinkedHashMap.java:555)
	at java.base/java.util.LinkedHashMap$LinkedValues.toArray(LinkedHashMap.java:639)
	at dev.jb0s.blockgameenhanced.gui.hud.immersive.widget.pickups.ImmersivePickupStream.getPickupsSafe(ImmersivePickupStream.java:90)
	at dev.jb0s.blockgameenhanced.gui.hud.immersive.widget.pickups.ImmersivePickupStream.render(ImmersivePickupStream.java:23)
	at dev.jb0s.blockgameenhanced.gui.hud.immersive.ImmersiveIngameHud.method_1759(ImmersiveIngameHud.java:49)
	at net.minecraft.class_329.method_1753(class_329.java:226)

-- Affected level --
Details:
	All players: 1 total; [class_746['TribbsOfTavern'/27701323, l='ClientLevel', x=1291.30, y=2.00, z=-1109.42]]
	Chunk stats: 625, 313
	Level dimension: minecraft:resource
	Level spawn location: World: (-953,58,203), Section: (at 7,10,11 in -60,3,12; chunk contains blocks -960,-64,192 to -945,319,207), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Level time: 96363 game time, 10272363 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 673870232 bytes (642 MiB) / 1577058304 bytes (1504 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33580.04
	Virtual memory used (MB): 22029.20
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 981.68
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blockgameenhanced: Blockgame Enhanced 1.2.4
			com_kohlschutter_junixsocket_junixsocket-common: junixsocket-common 2.8.3
			com_kohlschutter_junixsocket_junixsocket-native-common: junixsocket-native-common 2.8.3
			io_github_cdagaming_discordipc: DiscordIPC 0.6.1
		cloth-config: Cloth Config v6 6.5.102
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.24
		java: OpenJDK 64-Bit Server VM 17
		journeymap-fabric: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.18.2-1.9-fabric-SNAPSHOT
		minecraft: Minecraft 1.18.2
	Launched Version: fabric-loader-0.14.24-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.99, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 

<sub>[BGE-19](https://linear.app/blockgame-enhanced/issue/BGE-19/occasional-crashing-on-entity-pickup)</sub>

**Comment by jakkodude** [comment]
Heya, thank you for the report. Will investigate.

**Comment by TheInfamousAlk** [comment]
https://mclo.gs/C0L5mrt

Similar crash, here is the log.

**Comment by jakkodude** [comment]
Heyas, this should be fixed in yesterday's release. Thank you!
