### ISSUE TITLE
Inventory Tooltip Unreadable Due to Offset

### ISSUE THREAD

**Issue by EnderGonick** [jb0s/blockgame-enhanced#20]
Bug Description:
Upon opening the inventory, the offset of the tooltip for items makes it completely impossible to read anything more than the upper left quadrant of most items. Attempted to fix with a smart tooltip placement mod, was largely overridden by whatever implementation this mod has. Screenshots provided below.

Steps to Reproduce:
1. Clean install of Fabric API, Cloth Config, and Blockgame Enhanced in a fresh minecraft directory.
2. Launch game and join server.
3. Open Inventory
4. Hover over an item

Expected Behavior:
Minecraft places the tooltip roughly in the vicinity of the item. While often placed and text-wrapped poorly, still has a decently readable percentage of the tooltip, and can often be fixed by adjusting gui settings.

Actual behavior:
The tooltip is shoved into the bottom right corner of the inventory screen, and is largely illegible. Cannot be adjusted by changing GUI size. When a smart tooltip mod is added and the tooltip's position is forced into the top left corner, said tooltip is instead placed on top left corner of inventory, not top left of inventory screen. Screenshots provided.

Screenshots

1. Blockgame, GUI Size 4, No Smart Tooltips:    
![Inventory_SS_No_Smart_Tooltip_GUI_Size_4](https://github.com/jb0s/blockgame-enhanced/assets/16639576/8dac8583-dddf-41f8-95b0-ed7336666251)

2. Blockgame, GUI Size 1, No Smart Tooltips:
![Inventory_SS_No_Smart_Tooltip_GUI_Size_1](https://github.com/jb0s/blockgame-enhanced/assets/16639576/0515298d-6ab0-4167-8831-31fcd7139550)

3. Blockgame, GUI Size 4, Smart Tooltips:
![Inventory_SS_Smart_Tooltip_GUI_Size_4](https://github.com/jb0s/blockgame-enhanced/assets/16639576/eeb0dedc-6b87-4426-a9bd-5e80e5ab5774)

4. Blockgame, GUI Size 1, Smart Tooltips:
![Inventory_SS_No_Smart_Tooltip_GUI_Size_1](https://github.com/jb0s/blockgame-enhanced/assets/16639576/9b339bbc-a85f-41fd-9f23-23e03fbe9238)

5. No Blockgame, GUI Size 4, Smart Tooltips:
![Inventory_SS_NoBlockGame_+Smart_Tooltips_GUI_Size_4](https://github.com/jb0s/blockgame-enhanced/assets/16639576/e3e43d5c-69f9-4424-8009-f442af603a9d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - List of all mods you're using: 
      - Blockgame Enhanced, Cloth Config, Fabric API (for non-smart tooltips)
      - [Adaptive Tooltips](https://modrinth.com/mod/adaptive-tooltips), [YetAnotherConfigLib](https://modrinth.com/mod/yacl), Mod Menu (for smart tooltips)

**Comment by maciek134** [comment]
This was fixed in 7e2b250ed4db0285e77818b5cde4b3c99d9162fc
