### ISSUE TITLE
Current players in ping count is incorrect

### ISSUE THREAD

**Issue by adamsong** [jb0s/blockgame-enhanced#22]
**Describe the bug**
Ping count in main menu is incorrect, server is full at 30 players, message states "There are 13 players online" with the last line says "... and 18 more ..."

**To Reproduce**
1. Go to main menu
2. Observe the top left of the screen

**Expected behavior**
The online players count should be 30 (The number of players online)

**Actual behavior**
The online player count is 13

**Screenshots**
![image](https://github.com/jb0s/blockgame-enhanced/assets/4607006/b62f3098-7278-49f6-be20-3f04c3912dc5)

**Desktop (please complete the following information):**
 - OS: Artix
 - Architectury
 - Blockgame
 - Cloth Config
 - Fabric API
 - Jade
 - REI
 - Sodium

**Comment by jakkodude** [comment]
Fixed in #24.
