### ISSUE TITLE
Issue with rendering toolbar

### ISSUE THREAD

**Issue by BondarenkoArtur** [jb0s/blockgame-enhanced#23]
**Describe the bug**
When air bottle is visible on the screen, numbers are dissapearing. (Going behind background)

**To Reproduce**
1. Install plugin
2. Jump into water

**Expected behavior**
* Numbers are visible correctly, not dependent on air bottle or other items.

**Actual behavior**
Order of rendering items are strange, background goes before text if some elements (air bottle) are visible 

**Screenshots**
![image](https://github.com/jb0s/blockgame-enhanced/assets/9720950/87ffb440-2cac-4ac8-be09-abe03511ef8d)
![image](https://github.com/jb0s/blockgame-enhanced/assets/9720950/23b7b072-5111-4008-9c60-fc1193930458)

**Desktop (please complete the following information):**
 - OS: Linux steamdeck 6.1.52-valve9-1-neptune-61
 - List of all mods you're using: [Fabulously Optimized modpack](https://modrinth.com/modpack/fabulously-optimized) and this mod v1.3.1

**Comment by jakkodude** [comment]
Investigating.

**Comment by jakkodude** [comment]
Fixed in [04a9b36](https://github.com/jb0s/blockgame-enhanced/commit/04a9b365ec8909e08e10b7fcffe55dd886a45d55).
